# Implement your install deployment tasks here
# -------------------------------------------------

- name: install the RHADP parts
  ansible.builtin.import_tasks: install_rhadp.yml

- name: import repos
  ansible.builtin.import_tasks: import_repos.yml

- name: jumpstarter operator
  ansible.builtin.import_tasks: install_jumpstarter.yml

- name: patch backstage config
  ansible.builtin.import_tasks: patch_backstage.yml
