# Implement your install deployment tasks here
# -------------------------------------------------

- name: disable gitops sync
  shell: |
    oc patch apps backstage-gitops -n openshift-gitops --type=json -p '[{"op": "remove", "path": "/spec/syncPolicy/automated"}]'
    oc patch apps backstage -n openshift-gitops --type=json -p '[{"op": "remove", "path": "/spec/syncPolicy/automated"}]'
  ignore_errors: true

- name: create backstage config file
  template:
    src: "templates/app-config.yaml.j2"
    dest: "/tmp/app-config.yaml"

- name: replace backstage configmap
  shell: |
    oc delete configmap backstage-developer-hub-app-config -n backstage
    oc create configmap backstage-developer-hub-app-config --from-file=/tmp/app-config.yaml -n backstage
    oc label --overwrite configmap backstage-developer-hub-app-config rht-gitops.com/openshift-gitops=backstage -n backstage

- name: start backstage re-deployment
  shell: |
    oc delete pods --selector=app.kubernetes.io/name=developer-hub -n backstage
